#
#  Copyright 2022 Davide Bettio <davide@uninstall.it>
#
#  SPDX-License-Identifier: Apache-2.0 OR LGPL-2.1-or-later
#

name: ESP32 Builds

on:
  push: []
  pull_request: []

concurrency:
  group: ${{ github.workflow }}-${{ github.ref != 'refs/heads/main' && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  esp-idf:
    runs-on: ubuntu-22.04
    container: espressif/idf:v${{ matrix.idf-version }}

    strategy:
      fail-fast: false

      matrix:
        idf-version:
        - '4.4.6'
        - '5.0.6'
        - '5.1.3'

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        repository: 'atomvm/AtomVM'

    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        path: './src/platforms/esp32/components/'

    - name: Build with idf.py
      shell: bash
      working-directory: ./src/platforms/esp32/
      run: |
        . $IDF_PATH/export.sh
        idf.py reconfigure
        idf.py build
        idf.py size
    - name: Print component size info with idf.py
      shell: bash
      working-directory: ./src/platforms/esp32/
      run: |
        . $IDF_PATH/export.sh
        idf.py size-components
